name: Build Windows EXE

on:
  push:
    branches: [main] # Сборка будет запускаться каждый раз, когда ты делаешь push

jobs:
  build:
    runs-on: windows-latest # Запускаем на сервере с Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Если у тебя будут другие библиотеки, добавь их сюда

      - name: Build EXE
        run: pyinstaller --onefile --noconsole --name "SuperRenamer" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executable
          path: dist/SuperRenamer.exe
